### Configurable options
# Root project file(s) (without .tex)
MAIN:=user_manual
# Default output format [ps|pdf]
DEFAULT:=pdf
# Generate pdf from ps (either use pdflatex)
PS2PDF:=n
# Extra options for rubber
REXTRAOPTS:=
# Extra directories to "make"
PRE_EXTRADIRS:=
POST_EXTRADIRS:=
# Extra objectives to "make" (need <obj>, <obj>-clean and <obj>-distclean)
PRE_EXTRAOBJS:=
POST_EXTRAOBJS:=



### Project-specific extra objectives
# Add here your own rules (listed in $(PRE_EXTRAOBJS) and $(POST_EXTRAOBJS))


include templates/Makefile

